// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamp.Beacon;

#nullable disable

namespace Tamp.Beacon.Migrations
{
    [DbContext(typeof(BeaconDbContext))]
    partial class BeaconDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tamp.Beacon.Models.AuthAuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("text")
                        .HasColumnName("remote_ip");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AtUtc")
                        .HasDatabaseName("ix_auth_audit_log_at");

                    b.HasIndex("Event")
                        .HasDatabaseName("ix_auth_audit_log_event");

                    b.ToTable("auth_audit_log", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Build", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CiVendor")
                        .HasColumnType("text")
                        .HasColumnName("ci_vendor");

                    b.Property<string>("CliVersion")
                        .HasColumnType("text")
                        .HasColumnName("cli_version");

                    b.Property<int>("CommandsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("commands_total");

                    b.Property<long>("DurationNs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ns");

                    b.Property<int>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<string>("FailureTarget")
                        .HasColumnType("text")
                        .HasColumnName("failure_target");

                    b.Property<string>("HostArch")
                        .HasColumnType("text")
                        .HasColumnName("host_arch");

                    b.Property<string>("HostOs")
                        .HasColumnType("text")
                        .HasColumnName("host_os");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<long>("PeakMemoryBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("peak_memory_b");

                    b.Property<string>("ProjectArea")
                        .HasColumnType("text")
                        .HasColumnName("project_area");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<string>("RawTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_tags");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<long>("StartedUnixNs")
                        .HasColumnType("bigint")
                        .HasColumnName("started_unix_ns");

                    b.Property<int>("TargetsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("targets_failed");

                    b.Property<int>("TargetsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("targets_total");

                    b.HasKey("Id");

                    b.HasIndex("Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_builds_seq");

                    b.HasIndex("StartedUnixNs")
                        .HasDatabaseName("ix_builds_started");

                    b.HasIndex("Outcome", "StartedUnixNs")
                        .HasDatabaseName("ix_builds_outcome");

                    b.HasIndex("ProjectName", "ProjectArea")
                        .HasDatabaseName("ix_builds_project");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Command", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArgsCount")
                        .HasColumnType("integer")
                        .HasColumnName("args_count");

                    b.Property<double>("CpuTotalMs")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_total_ms");

                    b.Property<long>("DurationNs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ns");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executable");

                    b.Property<int>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<long>("PeakMemoryBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("peak_memory_b");

                    b.Property<string>("RawTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_tags");

                    b.Property<long>("StderrBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("stderr_bytes");

                    b.Property<long>("StdoutBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("stdout_bytes");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("Executable")
                        .HasDatabaseName("ix_commands_exe");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_commands_target");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtUnixNs")
                        .HasColumnType("bigint")
                        .HasColumnName("at_unix_ns");

                    b.Property<long>("BuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("build_id");

                    b.Property<long?>("CommandId")
                        .HasColumnType("bigint")
                        .HasColumnName("command_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RawTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_tags");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_events_build");

                    b.HasIndex("CommandId");

                    b.HasIndex("TargetId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.IdentityProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_providers_kind");

                    b.ToTable("identity_providers", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.IdentityProviderLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderId", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_provider_links_sub");

                    b.ToTable("identity_provider_links", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.ProjectMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_members_pair");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.ProjectToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_tokens_project");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_project_tokens_hash");

                    b.ToTable("project_tokens", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.PushSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaFilter")
                        .HasColumnType("text")
                        .HasColumnName("area_filter");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<long>("CreatedUnixNs")
                        .HasColumnType("bigint")
                        .HasColumnName("created_unix_ns");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<string>("ProjectFilter")
                        .HasColumnType("text")
                        .HasColumnName("project_filter");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_endpoint");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.SetupState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<string>("PendingTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("pending_token_hash");

                    b.Property<DateTimeOffset?>("PendingTokenIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_token_issued_at");

                    b.HasKey("Id");

                    b.ToTable("setup_state", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Target", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("build_id");

                    b.Property<int>("CommandsCount")
                        .HasColumnType("integer")
                        .HasColumnName("commands_count");

                    b.Property<double>("CpuTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_time_ms");

                    b.Property<long>("DurationNs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ns");

                    b.Property<long>("GcAllocatedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("gc_allocated_b");

                    b.Property<int>("GcGen0")
                        .HasColumnType("integer")
                        .HasColumnName("gc_gen0");

                    b.Property<int>("GcGen1")
                        .HasColumnType("integer")
                        .HasColumnName("gc_gen1");

                    b.Property<int>("GcGen2")
                        .HasColumnType("integer")
                        .HasColumnName("gc_gen2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phase")
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("RawTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_tags");

                    b.Property<long>("StartedUnixNs")
                        .HasColumnType("bigint")
                        .HasColumnName("started_unix_ns");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_targets_build");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_targets_name");

                    b.ToTable("targets", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tamp.Beacon.Models.AuthAuditLogEntry", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Command", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.Target", "Target")
                        .WithMany("Commands")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Event", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.Build", "Build")
                        .WithMany("Events")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Beacon.Models.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tamp.Beacon.Models.Target", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Build");

                    b.Navigation("Command");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.IdentityProviderLink", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.IdentityProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Beacon.Models.User", "User")
                        .WithMany("IdentityProviderLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Project", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.ProjectMember", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Beacon.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.ProjectToken", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tamp.Beacon.Models.Project", "Project")
                        .WithMany("Tokens")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Target", b =>
                {
                    b.HasOne("Tamp.Beacon.Models.Build", "Build")
                        .WithMany("Targets")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Build", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.Target", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Tamp.Beacon.Models.User", b =>
                {
                    b.Navigation("IdentityProviderLinks");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
